site_name: AsBuiltReport.Cohesity.DataPlatform
repo_url: https://github.com/AsBuiltReport/AsBuiltReport.Cohesity.DataPlatform
theme: readthedocs
edit_uri: edit/master/docs/
pages:
- Home: index.md
- AsBuiltReport.Cohesity.DataPlatform Basics:
  - What is AsBuiltReport.Cohesity.DataPlatform: about.md
  - Quick Start: Quick-Start-Installation-and-Example.md
- Basic Commands:
- Examples:
- Acknowledgements: acknowledgements.md
